import type { RequestStatus, DashboardStatistics, RequestDetail } from "@/types/dashboard"

export const mockStatistics: DashboardStatistics = {
  totalRequests: 12,
  pendingRequests: 5,
  completedRequests: 7,
  averageProcessingTime: 5,
}

export const mockRequests: RequestStatus[] = [
  {
    id: "req_001",
    ticketNumber: "F137-2024-001",
    learnerName: "Juan Dela Cruz",
    learnerReferenceNumber: "123456789012",
    status: "submitted",
    submittedDate: "2024-01-15T10:30:00Z",
    estimatedCompletion: "2024-01-22T17:00:00Z",
    requestType: "Original Copy",
    deliveryMethod: "pickup",
    requesterName: "Maria Dela Cruz",
    requesterEmail: "maria.delacruz@email.com",
    comments: [
      {
        id: "comment_001",
        message: "Your request has been received and is being processed.",
        registrarName: "Ms. Santos",
        timestamp: "2024-01-15T10:35:00Z",
        type: "info",
        requiresResponse: false,
      },
    ],
  },
  {
    id: "req_002",
    ticketNumber: "F137-2024-002",
    learnerName: "Maria Santos",
    learnerReferenceNumber: "123456789013",
    status: "requires-clarification",
    submittedDate: "2024-01-14T14:20:00Z",
    estimatedCompletion: "2024-01-21T17:00:00Z",
    requestType: "Certified True Copy",
    deliveryMethod: "mail",
    requesterName: "Pedro Santos",
    requesterEmail: "pedro.santos@email.com",
    comments: [
      {
        id: "comment_002",
        message: "We need additional verification documents. Please provide a valid ID.",
        registrarName: "Mr. Reyes",
        timestamp: "2024-01-16T09:15:00Z",
        type: "clarification-needed",
        requiresResponse: true,
      },
    ],
  },
  {
    id: "req_003",
    ticketNumber: "F137-2024-003",
    learnerName: "Jose Garcia",
    learnerReferenceNumber: "123456789014",
    status: "completed",
    submittedDate: "2024-01-10T11:45:00Z",
    estimatedCompletion: "2024-01-17T17:00:00Z",
    requestType: "Original Copy",
    deliveryMethod: "pickup",
    requesterName: "Ana Garcia",
    requesterEmail: "ana.garcia@email.com",
    comments: [
      {
        id: "comment_003",
        message: "Your Form 137 is ready for pickup. Please bring a valid ID.",
        registrarName: "Ms. Cruz",
        timestamp: "2024-01-17T15:30:00Z",
        type: "completion",
        requiresResponse: false,
      },
    ],
  },
  {
    id: "req_004",
    ticketNumber: "F137-2024-004",
    learnerName: "Anna Reyes",
    learnerReferenceNumber: "123456789015",
    status: "processing",
    submittedDate: "2024-01-16T16:10:00Z",
    estimatedCompletion: "2024-01-23T17:00:00Z",
    requestType: "Certified True Copy",
    deliveryMethod: "pickup",
    requesterName: "Carlos Reyes",
    requesterEmail: "carlos.reyes@email.com",
    comments: [
      {
        id: "comment_004",
        message: "Your request is currently being processed by our records department.",
        registrarName: "Ms. Torres",
        timestamp: "2024-01-17T08:20:00Z",
        type: "update",
        requiresResponse: false,
      },
    ],
  },
  {
    id: "req_005",
    ticketNumber: "F137-2024-005",
    learnerName: "Miguel Torres",
    learnerReferenceNumber: "123456789016",
    status: "ready-for-pickup",
    submittedDate: "2024-01-12T13:25:00Z",
    estimatedCompletion: "2024-01-19T17:00:00Z",
    requestType: "Original Copy",
    deliveryMethod: "pickup",
    requesterName: "Rosa Torres",
    requesterEmail: "rosa.torres@email.com",
    comments: [
      {
        id: "comment_005",
        message: "Your document is ready for pickup at the registrar office.",
        registrarName: "Mr. Lopez",
        timestamp: "2024-01-19T14:45:00Z",
        type: "completion",
        requiresResponse: false,
      },
    ],
  },
]

export const mockRequestDetails: RequestDetail[] = [
  {
    id: "req_001",
    ticketNumber: "F137-2024-001",
    learnerName: "Juan Dela Cruz",
    status: "submitted",
    submittedDate: "2024-01-15T10:30:00Z",
    estimatedCompletion: "2024-01-22T17:00:00Z",
    deliveryMethod: "pickup",
    purpose: "College enrollment",
    requesterEmail: "maria.delacruz@email.com",
    formData: {
      learnerReferenceNumber: "123456789012",
      learnerFirstName: "Juan",
      learnerMiddleName: "Santos",
      learnerLastName: "Dela Cruz",
      lastGradeLevel: "Grade 12",
      lastSchoolYear: "2023-2024",
      previousSchool: "Manila High School",
      requesterName: "Maria Dela Cruz",
      relationshipToLearner: "Mother",
      mobileNumber: "+63 912 345 6789",
      purpose: "College enrollment",
    },
    comments: [
      {
        id: "comment_001",
        message: "Your request has been received and is being processed.",
        author: "Ms. Santos",
        timestamp: "2024-01-15T10:35:00Z",
        type: "info",
      },
    ],
    timeline: [
      {
        description: "Request submitted",
        date: "2024-01-15T10:30:00Z",
        status: "submitted",
      },
    ],
  },
  {
    id: "req_002",
    ticketNumber: "F137-2024-002",
    learnerName: "Maria Santos",
    status: "requires-clarification",
    submittedDate: "2024-01-14T14:20:00Z",
    estimatedCompletion: "2024-01-21T17:00:00Z",
    deliveryMethod: "mail",
    purpose: "Job application",
    requesterEmail: "pedro.santos@email.com",
    formData: {
      learnerReferenceNumber: "123456789013",
      learnerFirstName: "Maria",
      learnerMiddleName: "Cruz",
      learnerLastName: "Santos",
      lastGradeLevel: "Grade 10",
      lastSchoolYear: "2022-2023",
      previousSchool: "Quezon City High School",
      requesterName: "Pedro Santos",
      relationshipToLearner: "Father",
      mobileNumber: "+63 917 654 3210",
      purpose: "Job application",
    },
    comments: [
      {
        id: "comment_002",
        message: "We need additional verification documents. Please provide a valid ID.",
        author: "Mr. Reyes",
        timestamp: "2024-01-16T09:15:00Z",
        type: "clarification-needed",
      },
    ],
    timeline: [
      {
        description: "Request submitted",
        date: "2024-01-14T14:20:00Z",
        status: "submitted",
      },
      {
        description: "Under review",
        date: "2024-01-15T09:00:00Z",
        status: "under-review",
      },
      {
        description: "Clarification needed",
        date: "2024-01-16T09:15:00Z",
        status: "requires-clarification",
      },
    ],
  },
]
